=== yvaernos/personalbudget/xml/inventory.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Student Name: Leonardo Amancio
    Student ID: 2017401
    Group: A
    Subject: Interactive Web Applications
    Lecturer: Mikhail Timofeev
    Author: Leonardo Amancio
    Code version: 1.0.0 02 Dec, 2020
    Availability: https://github.com/yvaernos/retail-stock
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
    <xs:element name="stock">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="products">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="product" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="sku" type="xs:string"/>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="product_url" type="xs:string"/>
                                        <xs:element name="thumbnail_url" type="xs:string"/>
                                        <xs:element name="price" type="xs:double"/>
                                        <xs:element name="retail_price" type="xs:double"/>
                                        <xs:element name="search_keywords" type="xs:string"/>
                                        <xs:element name="description" type="xs:string"/>
                                        <xs:element name="category" type="xs:string"/>
                                        <xs:element name="category_id" type="xs:positiveInteger"/>
                                        <xs:element name="brand" type="xs:string"/>
                                        <xs:element name="color" type="xs:string"/>
                                        <xs:element name="width" type="xs:decimal"/>
                                        <xs:element name="length" type="xs:decimal"/>
                                        <xs:element name="inventory_count" type="xs:positiveInteger"/>
                                        <xs:element name="date_created" type="xs:dateTime"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:positiveInteger"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== yvaernos/personalbudget/xml/inventory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Author: Leonardo Amancio
    Student ID: 2017401
    Group: A
    Subject: Interactive Web Applications
    Lecturer: Mikhail Timofeev
    Code version: 1.0.0 - 02 Dec, 2020
-->
<stock xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="inventory.xsd">
    <products>
        <product id=" 2343">
            <sku>leo-9133</sku>
            <name>fluffy pillow</name>
            <product_url>https://bit.ly/3nvecmm</product_url>
            <thumbnail_url>https://tinyurl.com/y9chrwz5</thumbnail_url>
            <price>24.99</price>
            <retail_price>24.99</retail_price>
            <search_keywords>fluffy, pillow, white</search_keywords>
            <description>it's really fluffy ...</description>
            <category>home</category>
            <category_id>0298</category_id>
            <brand>pillow master</brand>
            <colour>white</colour>
            <width>0.40</width>
            <length>0.20</length>
            <inventory_count>21</inventory_count>
            <date_created>2018-03-03T17:41:13</date_created>
        </product>
        <product id=" 2323">
            <sku>leo-9133</sku>
            <name>scruffy pillow</name>
            <product_url>https://bit.ly/3nvecmm</product_url>
            <thumbnail_url>https://bit.ly/3amdfx6</thumbnail_url>
            <price>24.99</price>
            <retail_price>24.99</retail_price>
            <search_keywords>fluffy, pillow, white</search_keywords>
            <description>it's really fluffy ...</description>
            <category>home</category>
            <category_id>0298</category_id>
            <brand>pillow master</brand>
            <colour>white</colour>
            <width>0.40</width>
            <length>0.20</length>
            <inventory_count>21</inventory_count>
            <date_created>2018-03-03T17:41:13</date_created>
        </product>
    </products>
</stock>
