=== yvaernos/personalbudget/xml/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Student Name: Leonardo Amancio
    Student ID: 2017401
    Group: A
    Subject: Interactive Web Applications
    Lecturer: Mikhail Timofeev
    Author: Leonardo Amancio
    Code version: 1.0.0 02 Dec, 2020
    Availability: https://github.com/yvaernos/retail-stock
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
    <xs:element name="userdetails">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="users">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="user" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="email" type="xs:string"/>
                                        <xs:element name="password" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:positiveInteger"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== yvaernos/personalbudget/xml/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Student Name: Leonardo Amancio
    Student ID: 2017401
    Group: A
    Subject: Interactive Web Applications
    Lecturer: Mikhail Timofeev
    Author: Leonardo Amancio
    Code version: 1.0.0 02 Dec, 2020
    Availability: https://github.com/yvaernos/retail-stock
-->

<userdetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="users.xsd">
    <users>
        <user id="001">
            <email>me@test.com</email>
            <password>123123</password>
        </user>
        <user id="002">
            <email>leo@test.com</email>
            <password>123123</password>
        </user>
    </users>
</userdetails>
